<a href="https://colab.research.google.com/github/jhasankbharadwaj/carprice_prediction/blob/main/Dynamic_Pricing_Suggestion_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Neural Networks - Programming Assignment
## Comparing Linear Models and Multi-Layer Perceptrons

**Student Name:** T V M V C Jhasank Bharadwaj

**Student ID:** 2025AG05622

In [13]:
#imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print('✓ Libraries imported successfully')

In [ ]:
df= pd.read_csv('/content/Retail-Supply-Chain-Sales-Dataset.csv', encoding='latin1')
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Retail Sales People,Product ID,Category,Sub-Category,Product Name,Returned,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Cassandra Brandow,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,Not,261.96,2,0.00,41.91
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Cassandra Brandow,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Not,731.94,3,0.00,219.58
2,3,CA-2016-138688,06-12-2016,06-12-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Anna Andreadi,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,Not,14.62,2,0.00,6.87
3,4,US-2015-108966,10-11-2015,10-11-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Cassandra Brandow,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,Not,957.58,5,0.45,-383.03
4,5,US-2015-108966,10-11-2015,10-11-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Cassandra Brandow,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,Not,22.37,2,0.20,2.52

In [ ]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858022,3.789574,0.156203,28.656973
std,2885.163629,32063.693350,623.245131,2.225110,0.206452,234.260203
min,1.000000,1040.000000,0.440000,1.000000,0.000000,-6599.980000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.730000
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.665000
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.360000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.980000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Row ID               9994 non-null   int64
 1   Order ID             9994 non-null   object
 2   Order Date           9994 non-null   object
 3   Ship Date            9994 non-null   object
 4   Ship Mode            9994 non-null   object
 5   Customer ID          9994 non-null   object
 6   Customer Name        9994 non-null   object
 7   Segment              9994 non-null   object
 8   Country              9994 non-null   object
 9   City                 9994 non-null   object
 10  State                9994 non-null   object
 11  Postal Code          9994 non-null   int64
 12  Region               9994 non-null   object
 13  Retail Sales People  9994 non-null   object
 14  Product ID           9994 non-null   object
 15  Category             9994 non-null   object
 16  Sub-Category         9994 non-null   object
 17  Product Name         9994 non-null   object
 18  Returned             9994 non-null   object
 19  Sales                9994 non-null   float64
 20  Quantity             9994 non-null   int64
 21  Discount             9994 non-null   float64
 22  Profit               9994 non-null   float64
dtypes: float64(3), int64(3), object(17)
memory usage: 1.8+ MB

train test split